### ISSUE TITLE
MỨC ĐỘ HOÀN THÀNH

### ISSUE THREAD

**Issue by thnam4500** [thnam4500/LTKHDL_FINAL#1]
- Giải thích sơ bộ về thông tin của bộ dữ liệu
- Nhận xét sơ bộ về dự liệu ban đầu
- Đặt câu hỏi và phân tích, trực quan hoá để trả lời câu hỏi
=> Đánh giá mức độ hoàn thành: 100%

**Comment by trisle0805** [comment]
Nhóm bạn có thể thêm một vài nội dung theo ý mình như sau:
1. Có mối liên hệ nào giữa các yếu tố **Kill, Gold, Experience** với **rồng hoặc sứ giả** ăn được so với đối thủ hay không ? Ví dụ, nếu cách biệt Gold hoặc Exp ở khoảng cách nào thì tỷ lệ ăn rồng giữa hai đội cao hơn và ảnh hưởng đến tỷ lệ thắng như thế nào ? Điều này có thể lợi dụng cột goldDiff hay expDiff thì phải. Ý của mình là nếu goldDiff như các bạn nhận xét ở cuối quá cách biệt so với đối thủ thì ăn sứ giả không tác dụng. Nhưng có nên tổ chức tranh chấp rồng hay không ? (Từ câu hỏi **Giả sử đội bạn đang ăn rồng, thì chúng ta nên ăn sứ giả, hay là tham gia tranh chấp rồng?**) Vì lúc đó team kia out đồ out exp hơn mình và nếu team thua thì sẽ tăng cách biệt hơn mà thôi, và khi đó có thể ta tổ chức ăn sứ giả để rút ngắn cách biệt nhiều nhất có thể hay nâng cao số Gold và Exp của đội thông qua farm lính ? (Bởi vì bạn nhận xét ăn sứ giả không có bất kì lợi thế nào nhưng theo mình thì không ăn mà đối thủ ăn khiến tỷ lệ win rate chắc chắn có cách biệt). Bạn cũng có thể thêm stackbar về vấn đề này và nhận xét định chuẩn giữa những thông số này có cách biệt như thế nào tới tỷ lệ thắng để vạch ra chiến lược ăn mục tiêu nào là hợp lý hơn.
2. Theo ý mình, ta có thể thêm dataframe và trực quan hoá về tỷ lệ thắng giữa hai đội với các tiêu chí như :
    -  Nếu một đội có goldDiff hoặc expDiff âm tranh chấp **rồng** hay **sứ giả** với đối thủ thì tỷ lệ thắng như thế nào ?
    - Đối với các đội chuyên nghiệp, kiểm soát tầm nhìn rất quan trọng. Liệu có mối liên hệ giữa tầm nhìn với tỷ lệ chiến thắng hay không ?
    - Đầu game là thời điểm trận đấu rất quan trọng và ảnh hưởng đến xuyên suốt cả ván đấu, liệu hơn vàng hoặc exp khoảng cách nào thì ta có thể đảm bảo tỷ lệ thắng luôn cao ?

**Comment by molr298** [comment]
Nhìn chung bài làm của nhóm hoàn thiện tốt, cũng như đã phân tích và trực quan cho người đọc thấy được các yếu tố trước phút thứ 10 ảnh hưởng như thế nào đến kết quả trận đấu. Tuy nhiên, nhóm có thể cải thiện để các biểu đồ dễ hiểu hơn và một số ý tưởng phân tích sâu hơn một tí:

- Trong các stackbarchart, các range [-3, -2], [-2, 1]... có ý nghĩa gì ở đây. Mặc dù với tiêu đề của từng chart cũng nhưng có chú thích về màu, nhưng mình vẫn không rõ lắm là win rate/lose rate này đại diện cho tỉ lệ thắng thua trong trường hợp cụ thể nào? Và tại sao lại có sự chênh lệch như thế? 
- gold và exp là các yếu tố quan trọng giúp chiến thắng trận đấu. Tuy nhiên ở các biểu đồ cũng có thể hiện rằng có những trận win với tỉ lệ gold hoặc exp thua thiệt so với đối thủ. Vậy ở các trường hợp này có một nguyên nhân cụ thể không, hay chỉ đơn thuần là kết quả tình huống (do combat hay, team địch di chuyển lỗi bị bắt lẻ, dẫn đến lội ngược dòng, hay không cẩn thận để bị backdoor....).
